title: Apache Solr Orbit
description: >-
  A performance benchmarking tool for Apache Solr clusters,
  derived from OpenSearch Benchmark.

url: https://apache.github.io
baseurl: /solr-orbit

# Site links used in templates
github_url: https://github.com/apache/solr-orbit
solr_url:   https://solr.apache.org

# Apply the default layout to all pages
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Markdown
sass:
  quiet_deps: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - README.md
