name: Check ASF Actions Compliance

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/**"
  pull_request:
    paths:
      - ".github/**"

permissions:
  contents: read

jobs:
  check:
    name: Check actions usage
    uses: apache/infrastructure-actions/.github/workflows/check-project-actions.yml@main
    permissions:
      contents: read
