---
name: dockerfile-lint

on:
  pull_request:
    paths:
      - 'docker/**'

permissions:
  contents: read

jobs:
  test_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: 'docker/*Dockerfile'
          annotate: false
